apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: voting-app-tekton
  name: voting-app-tekton
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: voting-app-tekton
    weight: 100