apiVersion: v1
kind: Service
metadata:
  name: voting-app-tekton
  namespace: gravensteiner
spec:
  selector:
    app: voting-app-tekton
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
