apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "voting.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: nb-172-104-231-206.frankfurt.nodebalancer.linode.com
      http:
        paths:
          - path: /voting(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "voting.name" . }}-service
                port:
                  number: 8080