apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting.name" . }}-service
  labels:
    app: {{ include "voting.name" . }}
spec:
  selector:
    app: {{ include "voting.name" . }}
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080